/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef DSHUTDOWN_PRIVATE_H
#define DSHUTDOWN_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.13"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	13
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"DShutdown.exe"
#define PRODUCT_NAME	"Distaff Shutdown Timer"
#define PRODUCT_VERSION	"1.0.0"

#endif /*DSHUTDOWN_PRIVATE_H*/
